version: '2.1'

services:
  nest:
    image: nest-banco-dados
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    links:
        - database
  database:
      image: mcr.microsoft.com/mssql/server
      environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: Zaq123*kiA
        MSSQL_PID: Express
      ports:
        - 1433:1433